apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: akv2k8s-controller-psp
  labels:
   app.kubernetes.io/component: akv2k8s-controller-psp
spec:
  privileged: true
  allowPrivilegeEscalation: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'secret'
  - 'configMap'
  - 'hostPath'
  hostPID: true
  hostIPC: true
  hostNetwork: true
  hostPorts:
  - min: 1
    max: 65536